// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ServiceModul.Model;

namespace ServiceModul.Migrations
{
    [DbContext(typeof(DBContext))]
    [Migration("20181112094001_dbinit3")]
    partial class dbinit3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ServiceModul.Model.FAQ", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Question");

                    b.Property<string>("Solution");

                    b.HasKey("ID");

                    b.ToTable("Faq");

                    b.HasData(
                        new { ID = 10, Question = "What is MovieMonster?", Solution = "MovieMonster is simply a original major streaming option for home television audiences.When it started nearly 20 years ago, MovieMonster was a subscription - based DVD service that would mailDVDs straight to your home." },
                        new { ID = 1, Question = "How can I buy movies?", Solution = "Make sure you have a registered account, then navigate to movies." },
                        new { ID = 2, Question = "Where does the name MovieMonster come from?", Solution = "Good question." },
                        new { ID = 3, Question = "How can I get a job at MovieMonster?", Solution = "We dont hire." },
                        new { ID = 4, Question = "Is is possible to rent movies only?", Solution = "Renting functionality will be supported soon." },
                        new { ID = 5, Question = "Who is the one?", Solution = "Neo is the one." },
                        new { ID = 6, Question = "What is the cheapest movie?", Solution = "All movies are cheap." },
                        new { ID = 7, Question = "How can I buy movies?", Solution = "Make sure you have a registered account, then navigate to movies." },
                        new { ID = 8, Question = "I forgot my password, what do I do?", Solution = "Send an email to moviemonster@support.com." },
                        new { ID = 9, Question = "What type of movies can I buy?", Solution = "MovieMonster support all kinds of movies." }
                    );
                });

            modelBuilder.Entity("ServiceModul.Model.QuestionModel", b =>
                {
                    b.Property<int>("QuestionID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Question");

                    b.Property<string>("QuestionSolution");

                    b.Property<string>("QuestionTopic");

                    b.Property<int>("Rating");

                    b.HasKey("QuestionID");

                    b.ToTable("Question");

                    b.HasData(
                        new { QuestionID = 1, Question = "Hello! I can't seem to buy movies from MovieMonster. What could be the problem?", QuestionSolution = "", QuestionTopic = "Can't buy movies. Help!", Rating = -5 },
                        new { QuestionID = 2, Question = "I accidentally committed the wrong files to Git, but I haven't pushed the commit to the server yet.How can I undo those commits from the local repository ? ", QuestionSolution = "$ git commit -m 'Something terribly misguided'$ git reset HEAD~<< edit files as necessary >>$ git add...$ git commit - c ORIG_HEAD    ", QuestionTopic = "How do I undo the most recent commits in Git?", Rating = 170 },
                        new { QuestionID = 3, Question = "Will you be adding livestreaming to MovieMonster?", QuestionSolution = "MovieMonster unfortunately doesn't support this function.", QuestionTopic = "Livestreaming function in the future?", Rating = 0 },
                        new { QuestionID = 4, Question = "Why is my account banned? help me pls", QuestionSolution = "", QuestionTopic = "My account is banned!!", Rating = 5 }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
